import React from "react"

export const Footer = () => {
    return (
        <> 
        <p>
        *TODOS LOS CAMPOS SON OBLIGATORIOS
        </p>
        <h4>Acepto políticas de privacidad</h4>

        <p>AL SUMINISTRARNOS TUS DATOS PERSONALES A L´OREAL ARGENTINA S.A., CONSENTÍS Y ACEPTÁS LA POLÍTICA DE PRIVACIDAD DE DATOS,
            LOS TÉRMINOS Y CONDICIONES DE USO Y NUESTRA POLÍTICA DE COOKIES. COMO TITULAR DE LOS DATOS PERSONALES TENÉS DERECHO A SOLICITAR EL ACCESO, RECTIFICACIÓN Y ACTUALIZACIÓN Y, EN SU CASO, SUPRESIÓN DE LOS MISMOS DE NUESTRA BASE DE DATOS DE CONFORMIDAD CON LA LEY 25.326 DE LA REPÚBLICA ARGENTINA.</p>

        </>
    )
  }
  export default Footer 